language: ruby
rvm:
    - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
  - gem install octokit
  
script:
  - git diff master.. -U0 README.md | grep -Po "(?<=^\+).*" >> temp.md
  - awesome_bot temp.md --allow-redirect
  - danger --verbose
